# Generated by Django 5.1.6 on 2025-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appointment_options_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=15),
        ),
    ]
