# Generated by Django 5.1.6 on 2025-02-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appointment_comments_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comments',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
