# Generated by Django 5.1.6 on 2025-02-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appointment_symptoms_alter_appointment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
