# Generated by Django 5.1.6 on 2025-02-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_appointment_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nurse'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=15),
        ),
        migrations.CreateModel(
            name='VitalsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, help_text='BP (e.g. 120/80 mmHg)', max_length=10, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart Rate (bpm)', null=True)),
                ('sugar_level', models.FloatField(blank=True, help_text='Blood Sugar (mg/dL)', null=True)),
                ('cholesterol', models.FloatField(blank=True, help_text='Cholesterol Level (mg/dL)', null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, help_text='Oxygen Saturation (%)', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Body Temperature (°C)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='accounts.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nurse')),
            ],
        ),
    ]
