# Generated by Django 5.1.6 on 2025-02-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appointment_nurse_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsrecord',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RenameField(
            model_name='vitalsrecord',
            old_name='recorded_by',
            new_name='nurse',
        ),
        migrations.RemoveField(
            model_name='vitalsrecord',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='vitalsrecord',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='vitalsrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='vitalsrecord',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='accounts.appointment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalsrecord',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsrecord',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsrecord',
            name='cholesterol_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalsrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='sugar_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
